DECLARE
	V_AUTHNAME AUTHOR.AUTHOR_LAST_NAME%TYPE;
BEGIN
	BEGIN
		SELECT AUTHOR_LAST_NAME
		INTO V_AUTHNAME
		FROM AUTHOR
		WHERE AUTHOR_STATE = V_AUTH_STATE;
	EXCEPTION
	WHEN TOO_MANY_ROWS THEN
		NULL;
	WHEN NO_DATA_FOUND THEN
		NULL;
	WHEN OTHERS THEN
		NULL;
	END;
END;